#!/usr/bin/env bash
# A Script to query and display information about subdomains.

get_info() {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomain="www lb-01 web-01 web-02"
    fi

    for sub in $subdomain; do
        result=$(dig +short "$sub.$domain" | awk '{print $1}')
        type=$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION' | awk '{print $4}')

        if [ -n "$result" ]; then
            echo "The subdomain $sub is a $type record and points to $result"
        fi
    done
}

if [ "$#" -eq 1 ]; then
    get_info "$1"
elif [ "$#" -eq 2 ]; then
    get_info "$1" "$2"
else
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi
