#!/usr/bin/env bash
#Install nginx and configuer the default html page

sudo apt-get update -y
sudo apt-get install nginx -y
sudo service nginx start
sudo chmod 644 /var/www/html/index.nginx-debian.html
sudo echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
