#!/usr/bin/env bash

# A bash scripts That catch the sigterm and all the signals.
File= "/var/run/myscript.pid"
cleanup() {
	  echo "Cleaning up and terminting script."
	  rm "$File"
	  exit
}

terminate() {
	   echo "I hate the kill command"
}

interrupt() {
	    echo "Y U no love me?!"
}
if [ ! -e $File ]
then
    echo echo "$$" >> "$File"
fi

trap cleanup SIGTERM SIGQUIT
trap terminate SIGTERM
trap interrupt SIGINT



while true
do
    echo "To infinity and beyond!"
    sleep 2
done
