#!/usr/bin/env bash
# Making a story from the passwd file.

passwd_file="/etc/passwd"

# Check if the file exits
if [ -e "$passwd_file" ]
then
	while IFS=: read -r username password uid gid info home shell
	do
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
	done < "$passwd_file"
else
echo "Error: /etc/passwd file does not exist."
fi
