#!/usr/bin/env bash
#Prints different texts on different iterations.

counter=1
while [ $counter -le 20 ]
do
	case $counter in
	    4 )
	     echo "$counter"
	     echo "bad luck from China"
	     ;;
	    9 )
	     echo "$counter"
	     echo "bad luck from Japan"
	     ;;
	    17 )
	     echo "$counter"
	     echo "bad luck from Italy"
	     ;;
	     * )
	     echo "$counter"
	     ;;
	esac
	(( counter++ ))
done
