#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes.

hour=0
while [ $hour -le 12 ]
do
    minutes=1
    echo "Hour: $hour"
    while [ $minutes -le 60 ]
    do
	if [ $minutes -eq 60 ]
	then
	    break
	else
	    echo "$minutes"
	fi
	(( minutes++ ))
    done
    (( hour++ ))
done
