#!/usr/bin/env bash
# Display the content of a directory.

for file in *;
do
	if [ -f "$file" ] && [[ ! "$file" =~ ^\. ]]
	then
		name_after_dash=$(echo "$file" | cut -d '-' -f 2-)
	echo "$name_after_dash"
	fi
done