#!/bin/bash
# Install and configure the firewall to block most traffic.

sudo apt-get update
sudo apt-get install ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw default 22/tcp
sudo ufw default 80/tcp
sudo ufw default 443/tcp
sudo ufw enable
